# Generated by Django 5.2.5 on 2025-08-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('sqlserver', 'SQL Server'), ('oracle', 'Oracle'), ('sqlite', 'SQLite'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('inserted_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Source Connection',
                'verbose_name_plural': 'Source Connections',
                'ordering': ['-created_at'],
                'unique_together': {('source_name', 'host', 'port')},
            },
        ),
    ]
